In [6]:
url = 'https://raw.githubusercontent.com/codebasics/py/master/DeepLearningML/13_dropout_layer/sonar_dataset.csv'
import pandas as pd
df = pd.read_csv(url,header=None, error_bad_lines=False)

In [7]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59  60  
0  0.0090  0.0032   R  
1  0.0052  0.0044   R  
2  0.0095  0.0078   R  
3  0.0040  0.0117   R  
4  0.0107  0.0094   R  

[5 rows x 61 columns]

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [10]:
df.shape

(208, 61)

In [14]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [15]:
df.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
           dtype='int64')

In [16]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [41]:
X=df.drop(60, axis=1)
y=df[60]
y.sample(5)

46     R
92     R
186    M
103    M
41     R
Name: 60, dtype: object

In [42]:
y = pd.get_dummies(y,drop_first=True)
y.sample(5)

R
118  0
93   1
52   1
120  0
18   1

In [43]:
y.R.value_counts()

0    111
1     97
Name: R, dtype: int64

In [46]:
X_train.shape, X_test.shape

((156, 60), (52, 60))

In [58]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=5)

In [59]:
import tensorflow as tf
from tensorflow import keras

In [92]:
model=keras.Sequential([
   keras.layers.Flatten(input_dim=60),
    keras.layers.Dense(60, activation='relu'),
    keras.layers.Dense(30, activation='relu'),
     keras.layers.Dense(15, activation='relu'),
     keras.layers.Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 0s 549us/step - loss: 0.6861 - accuracy: 0.6026
Epoch 2/100
20/20 [==============================] - 0s 549us/step - loss: 0.6712 - accuracy: 0.6282
Epoch 3/100
20/20 [==============================] - 0s 598us/step - loss: 0.6594 - accuracy: 0.6923
Epoch 4/100
20/20 [==============================] - 0s 499us/step - loss: 0.6389 - accuracy: 0.7436
Epoch 5/100
20/20 [==============================] - 0s 552us/step - loss: 0.6201 - accuracy: 0.7308
Epoch 6/100
20/20 [==============================] - 0s 598us/step - loss: 0.5895 - accuracy: 0.7500
Epoch 7/100
20/20 [==============================] - 0s 698us/step - loss: 0.5523 - accuracy: 0.8013
Epoch 8/100
20/20 [==============================] - 0s 549us/step - loss: 0.5133 - accuracy: 0.8077
Epoch 9/100
20/20 [==============================] - 0s 549us/step - loss: 0.4868 - accuracy: 0.7949
Epoch 10/100
20/20 [==============================] - 0s 499us/step - loss: 0.4616 - accura

In [61]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 997us/step - loss: 0.6063 - accuracy: 0.8269


[0.6063352227210999, 0.8269230723381042]

In [62]:
y_pred=model.predict(X_test).reshape(-1)
print(y_pred[:10])

y_pred=np.round(y_pred)
print(y_pred[:10])

[7.5392506e-07 9.9062258e-01 7.5385571e-03 1.4440411e-01 9.9992090e-01
 5.5389643e-07 9.3006039e-01 9.9999547e-01 1.8209219e-04 9.9998724e-01]
[0. 1. 0. 0. 1. 0. 1. 1. 0. 1.]


In [63]:
y_test[:10]

R
156  0
21   1
193  0
159  0
34   1
196  0
6    1
25   1
115  0
51   1

In [75]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.97      0.87        32
           1       0.92      0.60      0.73        20

    accuracy                           0.83        52
   macro avg       0.86      0.78      0.80        52
weighted avg       0.84      0.83      0.82        52



In [76]:
modeld=tf.keras.Sequential([
   tf.keras.layers.Dense(60, input_dim=60, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(30, activation='relu'),
    tf.keras.layers.Dropout(0.5),
     tf.keras.layers.Dense(15, activation='relu'),
     tf.keras.layers.Dropout(0.5),
     tf.keras.layers.Dense(1, activation='sigmoid')
])

modeld.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

modeld.fit(X_train, y_train, epochs=100, batch_size=8)

Epoch 1/100
20/20 [==============================] - 0s 986us/step - loss: 0.7122 - accuracy: 0.5513
Epoch 2/100
20/20 [==============================] - 0s 650us/step - loss: 0.7568 - accuracy: 0.5256
Epoch 3/100
20/20 [==============================] - 0s 598us/step - loss: 0.6991 - accuracy: 0.5128
Epoch 4/100
20/20 [==============================] - 0s 647us/step - loss: 0.6993 - accuracy: 0.5128
Epoch 5/100
20/20 [==============================] - 0s 697us/step - loss: 0.6883 - accuracy: 0.5769
Epoch 6/100
20/20 [==============================] - 0s 648us/step - loss: 0.6960 - accuracy: 0.5064
Epoch 7/100
20/20 [==============================] - 0s 698us/step - loss: 0.7018 - accuracy: 0.5256
Epoch 8/100
20/20 [==============================] - 0s 698us/step - loss: 0.6854 - accuracy: 0.5385
Epoch 9/100
20/20 [==============================] - 0s 698us/step - loss: 0.6992 - accuracy: 0.5000
Epoch 10/100
20/20 [==============================] - 0s 598us/step - loss: 0.6807 - accura

In [72]:
modeld.evaluate(X_test, y_test)

2/2 [==============================] - 0s 482us/step - loss: 0.3442 - accuracy: 0.8269


[0.3441932499408722, 0.8269230723381042]

In [73]:
y_pred=modeld.predict(X_test).reshape(-1)
print(y_pred[:10])

y_pred=np.round(y_pred)
print(y_pred[:10])

[0.05507207 0.78582394 0.09976527 0.33466956 0.8852798  0.02182871
 0.7848091  0.9874332  0.19567356 0.9958937 ]
[0. 1. 0. 0. 1. 0. 1. 1. 0. 1.]


In [74]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.97      0.87        32
           1       0.92      0.60      0.73        20

    accuracy                           0.83        52
   macro avg       0.86      0.78      0.80        52
weighted avg       0.84      0.83      0.82        52



In [77]:
a = np.array([[1,2,3], [4,5,6]])
a.shape

(2, 3)

In [88]:
a=np.reshape(a,(6))
a

array([1, 2, 3, 4, 5, 6])

In [89]:
a.shape

(6,)